from data import *

adjacency = {
	"Alaska": ["Kamchatka", "Territori del Nord Ovest", "Alberta"],
	"Alberta": ["Alaska", "Territori del Nord Ovest", "Ontario", "Stati Uniti Occidentali"],
	"America Centrale": ["Venezuela", "Stati Uniti Orientali", "Stati Uniti Occidentali"],
	"Stati Uniti Orientali": ["America Centrale", "Stati Uniti Occidentali", "Ontario", "Quebec"],
	"Groenlandia": ["Territori del Nord Ovest", "Ontario", "Quebec", "Islanda"],
	"Territori del Nord Ovest": ["Alaska", "Alberta", "Ontario", "Groenlandia"],
	"Ontario": ["Alberta", "Stati Uniti Occidentali", "Territori del Nord Ovest", "Stati Uniti Orientali", "Quebec", "Groenlandia"],
	"Quebec": ["Ontario", "Stati Uniti Orientali", "Groenlandia"],
	"Stati Uniti Occidentali": ["Alberta", "Ontario", "Stati Uniti Orientali", "America Centrale"],
	"Argentina": ["Perù", "Brasile"],
	"Brasile": ["Argentina", "Perù", "Venezuela", "Africa del Nord"],
	"Perù": ["Argentina", "Brasile", "Venezuela"],
	"Venezuela": ["Brasile", "Perù", "America Centrale"],
	"Gran Bretagna": ["Islanda", "Scandinavia", "Europa Settentrionale", "Europa Occidentale"],
	"Islanda": ["Groenlandia", "Gran Bretagna", "Scandinavia"],
	"Europa Settentrionale": ["Scandinavia", "Gran Bretagna", "Europa Occidentale", "Europa Meridionale", "Ucraina"],
	"Scandinavia": ["Islanda", "Gran Bretagna", "Europa Settentrionale", "Ucraina"],
	"Europa Meridionale": ["Europa Occidentale", "Europa Settentrionale", "Ucraina", "Medio Oriente", "Africa del Nord", "Egitto"],
	"Ucraina": ["Scandinavia", "Europa Settentrionale", "Europa Meridionale", "Medio Oriente", "Afghanistan", "Urali"],
	"Europa Occidentale": ["Gran Bretagna", "Europa Settentrionale", "Europa Meridionale", "Africa del Nord"],
	"Congo": ["Africa del Nord", "Africa Orientale", "Africa del Sud"],
	"Africa Orientale": ["Egitto", "Africa del Nord", "Congo", "Africa del Sud", "Madagascar"],
	"Egitto": ["Europa Meridionale", "Africa del Nord", "Africa Orientale", "Medio Oriente"],
	"Madagascar": ["Africa Orientale", "Africa del Sud"],
	"Africa del Nord": ["Europa Occidentale", "Europa Meridionale", "Brasile", "Egitto", "Congo", "Africa Orientale"],
	"Africa del Sud": ["Madagascar", "Africa Orientale", "Congo"],
	"Afghanistan": ["Ucraina", "Urali", "Cina", "Medio Oriente"],
	"Cina": ["Mongolia", "Siberia", "Urali", "Afghanistan", "Medio Oriente", "India", "Siam"],
	"India": ["Siam", "Medio Oriente", "Cina"],
	"Cita": ["Mongolia", "Siberia", "Jacuzia", "Kamchatka"],
	"Giappone": ["Kamchatka", "Mongolia"],
	"Kamchatka": ["Alaska", "Jacuzia", "Cita", "Mongolia", "Giappone"],
	"Medio Oriente": ["Europa Meridionale", "Egitto", "India", "Cina", "Afghanistan", "Ucraina"],
	"Mongolia": ["Cina", "Siberia", "Cita", "Kamchatka", "Giappone"],
	"Siam": ["Cina", "India", "Indonesia"],
	"Siberia": ["Jacuzia", "Cita", "Mongolia", "Cina", "Urali"],
	"Urali": ["Siberia", "Cina", "Afghanistan", "Ucraina"],
	"Jacuzia": ["Kamchatka", "Cita", "Siberia"],
	"Australia Orientale": ["Australia Occidentale", "Nuova Guinea"],
	"Indonesia": ["Siam", "Nuova Guinea", "Australia Occidentale"],
	"Nuova Guinea": ["Indonesia", "Australia Occidentale", "Australia Orientale"],
	"Australia Occidentale": ["Australia Orientale", "Nuova Guinea", "Indonesia"]
}

coord = {
	"Alaska": [(61, 95), (135, 147)],
	"Alberta": [(101, 196), (194, 246)],
	"America Centrale": [(44, 350), (130, 405)],
	"Stati Uniti Orientali": [(148, 330), (239, 378)],
	"Groenlandia": [(387, 55), (484, 107)],
	"Territori del Nord Ovest": [(155, 111), (250, 160)],
	"Ontario": [(204, 237), (283, 286)],
	"Quebec": [(292, 263), (374, 310)],
	"Stati Uniti Occidentali": [(55, 255), (155, 298)],
	"Argentina": [(109, 642), (197, 700)],
	"Brasile": [(165, 518), (275, 575)],
	"Perù": [(53, 560), (149, 617)],
	"Venezuela": [(119, 448), (242, 501)],
	"Gran Bretagna": [(432, 239), (514, 290)],
	"Islanda": [(475, 129), (554, 180)],
	"Europa Settentrionale": [(525, 288), (620, 333)],
	"Scandinavia": [(545, 187), (627, 237)],
	"Europa Meridionale": [(521, 349), (623, 409)],
	"Ucraina": [(627, 251), (708, 304)],
	"Europa Occidentale": [(400, 355), (503, 411)],
	"Congo": [(538, 614), (617, 658)],
	"Africa Orientale": [(622, 557), (717, 613)],
	"Egitto": [(551, 497), (677, 542)],
	"Madagascar": [(684, 700), (760, 742)],
	"Africa del Nord": [(420, 464), (506, 526)],
	"Africa del Sud": [(568, 684), (648, 746)],
	"Afghanistan": [(731, 297), (825, 346)],
	"Cina": [(939, 308), (1057, 380)],
	"India": [(844, 437), (925, 483)],
	"Cita": [(848, 190), (927, 234)],
	"Giappone": [(1035, 159), (1134, 210)],
	"Kamchatka": [(924, 74), (1003, 158)],
	"Medio Oriente": [(696, 430), (797, 479)],
	"Mongolia": [(905, 243), (992, 281)],
	"Siam": [(950, 419), (1037, 469)],
	"Siberia": [(771, 145), (839, 217)],
	"Urali": [(717, 219), (783, 271)],
	"Jacuzia": [(847, 76), (914, 150)],
	"Australia Orientale": [(1061, 718), (1146, 769)],
	"Indonesia": [(1012, 516), (1099, 581)],
	"Nuova Guinea": [(1110, 567), (1190, 626)],
	"Australia Occidentale": [(982, 654), (1072, 710)]
}

continents = {
	"America del Nord": ["Alaska","Alberta","America Centrale","Stati Uniti Orientali","Groenlandia","Territori del Nord Ovest","Ontario","Quebec","Stati Uniti Occidentali"],
	"America del Sud": ["Argentina","Brasile","Perù","Venezuela"],
	"Europa": ["Gran Bretagna","Islanda","Europa Settentrionale","Scandinavia","Europa Meridionale","Ucraina","Europa Occidentale"],
	"Africa": ["Congo","Africa Orientale","Egitto","Madagascar","Africa del Nord","Africa del Sud"],
	"Asia": ["Afghanistan","Cina","India","Cita","Giappone","Kamchatka","Medio Oriente","Mongolia","Siam","Siberia","Urali","Jacuzia"],
	"Oceania": ["Australia Orientale","Indonesia","Nuova Guinea","Australia Occidentale"]
}

continentsBonus = {
	"America del Nord": 5,
	"America del Sud": 2,
	"Europa": 5,
	"Africa": 3,
	"Asia": 7,
	"Oceania": 2
}

cardType = {
	"Alaska": FANTE,
	"Alberta": FANTE,
	"America Centrale": CAVALLO,
	"Stati Uniti Orientali": CANNONE,
	"Groenlandia": CAVALLO,
	"Territori del Nord Ovest": CANNONE,
	"Ontario": CAVALLO,
	"Quebec": CANNONE,
	"Stati Uniti Occidentali": FANTE,
	"Argentina": FANTE,
	"Brasile": CANNONE,
	"Perù": CAVALLO,
	"Venezuela": CANNONE,
	"Gran Bretagna": CAVALLO,
	"Islanda": FANTE,
	"Europa Settentrionale": CAVALLO,
	"Scandinavia": CANNONE,
	"Europa Meridionale": CAVALLO,
	"Ucraina": CANNONE,
	"Europa Occidentale": FANTE,
	"Congo": CAVALLO,
	"Africa Orientale": CANNONE,
	"Egitto": FANTE,
	"Madagascar": FANTE,
	"Africa del Nord": FANTE,
	"Africa del Sud": CANNONE,
	"Afghanistan": FANTE,
	"Cina": CAVALLO,
	"India": FANTE,
	"Cita": FANTE,
	"Giappone": FANTE,
	"Kamchatka": CAVALLO,
	"Medio Oriente": CANNONE,
	"Mongolia": CANNONE,
	"Siam": CANNONE,
	"Siberia": CANNONE,
	"Urali": CAVALLO,
	"Jacuzia": CAVALLO,
	"Australia Orientale": FANTE,
	"Indonesia": CAVALLO,
	"Nuova Guinea": CAVALLO,
	"Australia Occidentale": CANNONE
}